version: "3.8"

services:
  db:
    image: "postgres:14.1-alpine"
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres
    network_mode: bridge
